use anyhow::{Context, Result};
use std::path::Path;
use std::process::Command;

use crate::commands::build::{
    build_dir_for, handle_build, is_configured_for_generator, load_presets, preset_for,
    resolve_generator_for_preset,
};

/// Heuristic to detect whether CTest metadata exists for this build dir.
fn ctest_metadata_present(build_dir: &Path) -> bool {
    // Root ctest file or the TAG under Testing/
    if build_dir.join("CTestTestfile.cmake").exists()
        || build_dir.join("Testing").join("TAG").exists()
    {
        return true;
    }
    // Also consider a tests/ subdir generated by the test component
    let tests_dir = build_dir.join("tests");
    tests_dir.join("CTestTestfile.cmake").exists()
        || tests_dir.join("Testing").join("TAG").exists()
}

pub fn handle_test(path: &str, config: &str) -> Result<()> {
    // In unit tests, we allow skipping the heavy work.
    if std::env::var("TRITON_TEST_MODE").is_ok() {
        eprintln!("TRITON_TEST_MODE set — skipping actual build and tests");
        return Ok(());
    }

    let cfg = config.trim();
    let build_dir = build_dir_for(Path::new(path), cfg);

    // Decide if we need to (re)build first (to ensure test discovery exists).
    let needs_build = !build_dir.exists()
        || !ctest_metadata_present(&build_dir)
        || {
            let preset = preset_for(cfg);
            let components_dir = Path::new(path).join("components");
            let (_v, map) = load_presets(&components_dir)?;
            let mut guard = Vec::new();
            let effective_gen = resolve_generator_for_preset(&map, preset, &mut guard)
                .or_else(|| resolve_generator_for_preset(&map, "default", &mut guard))
                .unwrap_or_else(|| "Ninja".to_string());
            !is_configured_for_generator(&build_dir, &effective_gen)
        };

    if needs_build {
        eprintln!(
            "No usable build with tests for config '{}', running `triton build` first…",
            cfg
        );
        handle_build(path, cfg, false, false)?;
    }

    // Run ALL tests by default (works with gtest_discover_tests).
    // You can override with:
    //   TRITON_CTEST_FILTER="Regex"
    //   TRITON_CTEST_LABEL="label"
    //   TRITON_CTEST_JOBS="N"   (parallel ctest -j)
    let label = std::env::var("TRITON_CTEST_LABEL").ok();
    let filter = std::env::var("TRITON_CTEST_FILTER").unwrap_or_else(|_| String::from(".*"));
    let jobs = std::env::var("TRITON_CTEST_JOBS").ok();

    let mut cmd = Command::new("ctest");
    cmd.current_dir(&build_dir).arg("--output-on-failure");

    // On multi-config generators, direct ctest to the right config.
    // (Ignored by single-config generators like Ninja.)
    cmd.arg("-C").arg(match cfg.to_ascii_lowercase().as_str() {
        "release" | "rel" | "r" => "Release",
        _ => "Debug",
    });

    if let Some(j) = jobs {
        if !j.trim().is_empty() {
            cmd.arg("-j").arg(j.trim());
        }
    }

    if let Some(lbl) = label {
        cmd.arg("-L").arg(lbl);
    } else if filter != ".*" {
        // Only add -R if user gave a narrower regex; otherwise run everything
        cmd.arg("-R").arg(filter);
    }

    let status = cmd.status().context("failed to run ctest")?;
    if !status.success() {
        anyhow::bail!("Some tests failed");
    }

    Ok(())
}
